### ISSUE TITLE
Question: is this hello world template still recommended?

### ISSUE THREAD

**Issue by zommerfelds** [Brightspace/hello-world-fra-iframe#18]
Thank you for providing this template, I'm using it right now. However, I was wondering if anything here is outdated or if some tools/libraries should be replaced, since this was last updated early last year.

**Comment by dlockhart** [comment]
@zommerfelds Hi Christian -- I've just made a few updates that upgrade it to the latest `ifrau`, so yeah it's mostly up-to-date.

Having said that, it's a very simple demo app that merely demonstrates using `ifrau` to sync some settings and make a Valence API call. I would use it more for reference and as a playground than as a template.

**Comment by zommerfelds** [comment]
OK thanks!
