### ISSUE TITLE
Adopt iam-build-tokens

### ISSUE THREAD

**Issue by j3parker** [Brightspace/hello-world-fra-iframe#26]
Main tracking issue: https://github.com/Brightspace/iam-build-tokens/issues/191

For things on the CDN (FRAs or libraries) use [this documentation](https://github.com/Brightspace/iam-build-tokens/blob/master/docs/howto-cdn-users.md) specifically. Our experience with other teams is that it takes about 15 minutes of work.

This will replace the static IAM credentials your CI job is using with a set of temporary tokens which will be rotated every 6 hours.

If you have any concerns, questions, or have a special use-case don't hesitate to reach out.

**Comment by dlockhart** [comment]
Resolved!
